import asyncio
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from enum import Enum
from typing import AsyncGenerator, Generator, Optional

class LLMProvider(str, Enum):
    """Supported LLM providers."""
    CLAUDE = "claude"
    ANTHROPIC = "anthropic"  # Alias for CLAUDE
    OPENAI = "openai"

class ClaudeModel(str, Enum):
    """Anthropic Claude models."""
    CLAUDE_3_5_SONNET = "claude-3-5-sonnet-latest"
    CLAUDE_3_5_HAIKU = "claude-3-5-haiku-latest"
    # Legacy/variant-specific names from prompt experiments
    CLAUDE_SONNET_4_6 = "claude-sonnet-4-6"
    CLAUDE_HAIKU_4_5 = "claude-haiku-4-5-20251001"

class OpenAIModel(str, Enum):
    """OpenAI models."""
    GPT_4O = "gpt-4o"
    GPT_4O_MINI = "gpt-4o-mini"


@dataclass
class ToolDefinition:
    """Represents a tool definition that can be passed to an LLM."""
    name: str
    description: str
    input_schema: dict


@dataclass
class ToolCall:
    """Represents a tool call request generated by the LLM."""
    id: str
    name: str
    arguments: dict


@dataclass
class LLMResponse:
    """Unified response object returned by all provider clients."""
    text: str
    model: str
    input_tokens: int
    output_tokens: int
    cost_usd: float
    tool_calls: list[ToolCall] = field(default_factory=list)
    is_final: bool = False
    stop_reason: Optional[str] = None


class BaseLLMClient(ABC):
    """Abstract base class that all provider clients must implement. Exposes async and sync interfaces."""

    @abstractmethod
    async def generate(
        self,
        prompt: str,
        system_prompt: Optional[str] = None,
        model: Optional[str] = None,
        temperature: float = 0.0,
        max_tokens: int = 1000
    ) -> LLMResponse:
        """Asynchronously generates a single complete response from the LLM."""
        pass

    @abstractmethod
    async def generate_stream(
        self,
        prompt: str,
        system_prompt: Optional[str] = None,
        model: Optional[str] = None,
        temperature: float = 0.0,
        max_tokens: int = 1000
    ) -> AsyncGenerator[LLMResponse, None]:
        """Asynchronously streams generated response tokens from the LLM."""
        pass

    @abstractmethod
    async def generate_with_tools(
        self,
        prompt: str,
        tools: list[ToolDefinition],
        system_prompt: Optional[str] = None,
        model: Optional[str] = None,
        temperature: float = 0.0,
        max_tokens: int = 1000
    ) -> LLMResponse:
        """Asynchronously generates a response that may include tool calls."""
        pass

