# -*- coding: utf-8 -*-
"""nanoGPT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J4tu3lb2A7QkXoVXAKOBku-uBkOrIW41
"""

import os
import kagglehub
import numpy as np
import tiktoken  
import torch
import torch.nn as nn
from torch.nn import functional as F

# Download latest version
path = kagglehub.dataset_download("kaushaltiwari/tiny-shakespeare")

print("Path to dataset files:", path)


# List files in the download directory to confirm the filename
files = os.listdir(path)
print(f"Files in dataset: {files}")

# Load the content of the text file
# Using the correct filename 'tiny-shakespeare.txt' as seen in the folder contents
file_path = os.path.join(path, "tiny-shakespeare.txt")
with open(file_path, "r", encoding="utf-8") as f:
    raw_text = f.read()

# Wrap it in a structure similar to the previous 'ds' object for compatibility
ds = {"train": {"text": [raw_text]}, "validation": {"text": [""]}}

print(f"Dataset loaded. Total characters: {len(raw_text):,}")

print(ds)

text = "".join(ds["train"]["text"])
chars = sorted(list(set(text)))
vocab_size = len(chars)

print(f"Unique characters: {chars}")
print(f"Vocabulary size: {vocab_size}")


# Get a suitable encoding, e.g., 'gpt2'
# Other options include 'cl100k_base' for more recent models like GPT-4, GPT-3.5-turbo
enc = tiktoken.get_encoding("cl100k_base")


def encode(s):
    return enc.encode(s)


def decode(l):
    return enc.decode(l)


print("tiktoken encoder and decoder functions created.")

# Take a small sample of the 'text' to demonstrate
sample_text = text[:100]

# Encode the sample text
encoded_text = encode(sample_text)
print(f"Original sample text: {sample_text}")
print(f"Encoded text (token IDs): {encoded_text}")

# Decode the token IDs back to text
decoded_text = decode(encoded_text)
print(f"Decoded text: {decoded_text}")

# Verify if the decoded text matches the original (should be True for valid encoding/decoding)
print(f"Does decoded text match original? {decoded_text == sample_text}")


# To encode the entire dataset efficiently, we concatenate everything into one large sequence
# This is standard for training models like GPT where we sample random offsets

print("Encoding the entire training dataset...")
# We'll use a list comprehension and join them to avoid overhead
train_text = " ".join(ds["train"]["text"])
train_ids = encode(train_text)
train_data = torch.tensor(train_ids, dtype=torch.long)

print("Encoding the validation dataset...")
val_text = " ".join(ds["validation"]["text"])
val_ids = encode(val_text)
val_data = torch.tensor(val_ids, dtype=torch.long)

print(f"Train data tokens: {len(train_data):,}")
print(f"Val data tokens: {len(val_data):,}")

# Redefining data_tensor for compatibility with your next steps
data_tensor = train_data

n = int(0.9 * len(data_tensor))
train_data = data_tensor[:n]
val_data = data_tensor[n:]

print(f"Total samples: {len(data_tensor)}")
print(f"Training samples: {len(train_data)}")
print(f"Validation samples: {len(val_data)}")

context_size = 8
train_data[: context_size + 1]

x = train_data[:context_size]
y = train_data[1 : context_size + 1]
for t in range(context_size):
    context = x[: t + 1]
    target = y[t]
    print(f"when input is {context} the target: {target}")

torch.manual_seed(1337)
# Note: batch_size and block_size are defined globally


def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == "train" else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i : i + block_size] for i in ix])
    y = torch.stack([data[i + 1 : i + block_size + 1] for i in ix])
    return x, y


# Test call with the initial small batch size
batch_size = 4
block_size = 8
xb, yb = get_batch("train")
print(f"Inputs shape: {xb.shape}")
print(f"Targets shape: {yb.shape}")


torch.manual_seed(1337)


class BigramLanguageModel(nn.Module):
    def __init__(self, vocab_size):
        super().__init__()
        # Each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)

    def forward(self, idx, targets=None):
        # idx and targets are both (B,T) tensor of integers
        logits = self.token_embedding_table(idx)  # (B,T,C)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B * T, C)
            targets = targets.view(B * T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # Get the predictions
            logits, loss = self(idx)
            # Focus only on the last time step
            logits = logits[:, -1, :]  # becomes (B, C
            probs = F.softmax(logits, dim=-1)  # (B, C)
            # Sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1)  # (B, 1)

            idx = torch.cat((idx, idx_next), dim=1)  # (B, T+1)
        return idx


# Fix: Use enc.n_vocab because we used tiktoken for encoding,
# not the character-level vocab_size.
model_vocab_size = enc.n_vocab
model = BigramLanguageModel(model_vocab_size)

logits, loss = model(xb, yb)
print(f"Logits shape: {logits.shape}")
print(f"Loss: {loss}")

print(
    decode(
        model.generate(idx=torch.zeros((1, 1), dtype=torch.long), max_new_tokens=100)[
            0
        ].tolist()
    )
)

optimizer = torch.optim.AdamW(model.parameters(), lr=1e-3)

batch_size = 32
optimizer = torch.optim.AdamW(model.parameters(), lr=1e-3)

print("Training...")
for steps in range(1000):
    xb, yb = get_batch("train")

    # evaluate loss
    logits, loss = model(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

    if steps % 200 == 0:
        print(f"Step {steps}: loss {loss.item():.4f}")

print(f"Final loss: {loss.item():.4f}")
print("\nGenerated text after training:")
context = torch.zeros((1, 1), dtype=torch.long)
print(decode(model.generate(context, max_new_tokens=100)[0].tolist()))

print(
    decode(
        model.generate(idx=torch.zeros((1, 1), dtype=torch.long), max_new_tokens=100)[
            0
        ].tolist()
    )
)


log_file = "app.log"
if os.path.exists(log_file):
    print(f"Reading {log_file}...\n" + "-" * 30)
    with open(log_file, "r") as f:
        print(f.read())
else:
    print(f"Error: {log_file} not found in the current directory.")
    print("Available files:", os.listdir("."))
